### ISSUE TITLE
Migrations failing when upgrading from 0.7.10 to 0.8.1

### ISSUE THREAD

**Issue by juanpedrojose** [karafka/karafka-web#263]
I was upgrading my project from `karafka-web 0.7.10` to `karafka-web 0.8.1` and encountered an issue on my staging environment (**not observing locally**), it seems that in my case migrations are failing which causes `bundle exec karafka server` to not start.

```ruby
 @@@                                             @@@@@  @@@
@@@                                            @@@     @@@
@@@  @@@    @@@@@@@@@   @@@ @@@   @@@@@@@@@  @@@@@@@@  @@@  @@@@   @@@@@@@@@
@@@@@@     @@@    @@@   @@@@@    @@@    @@@    @@@     @@@@@@@    @@@    @@@
@@@@@@@    @@@    @@@   @@@     @@@@    @@@    @@@     @@@@@@@    @@@    @@@
@@@  @@@@  @@@@@@@@@@   @@@      @@@@@@@@@@    @@@     @@@  @@@@   @@@@@@@@@@


Upgrade to Karafka Pro for more features and support: https://karafka.io
#<Thread:0x000000011091e608 /Users/alex/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/karafka-2.3.0/lib/karafka/helpers/async.rb:25 run> terminated with exception (report_on_exception is true):
/Users/alex/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/karafka-web-0.8.1/lib/karafka/web/management/migrations/1704722380_split_listeners_into_active_and_paused_in_metrics.rb:18:in `block (2 levels) in migrate': undefined method `to_i' for {:active=>8, :standby=>0}:Hash (NoMethodError)

                              metric.last[:listeners].to_i
                                                     ^^^^^
Did you mean?  to_s
               to_a
               to_h
	from /Users/alex/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/karafka-web-0.8.1/lib/karafka/web/management/migrations/1704722380_split_listeners_into_active_and_paused_in_metrics.rb:16:in `each'
```

--------

## Expected behavior

`$ bundle exec karafka server` executes with no errors

## Actual behavior

Seems that when `karafka-web 0.8.1` is executing migrations it fails when trying to transform listeners info to new format in migrations.

When running

```bash
$ bundle exec karafka-web migrate
```

or

```bash
$ bundle exec karafka-web reset
```

I get an exception

```bash
Resetting Karafka Web UI...

Removing karafka_consumers_states...
Topic karafka_consumers_states successfully deleted.
Removing karafka_consumers_reports...
Topic karafka_consumers_reports successfully deleted.
Removing karafka_consumers_metrics...
Topic karafka_consumers_metrics successfully deleted.
Removing karafka_errors...
Topic karafka_errors successfully deleted.

Creating topic karafka_errors...
Topic karafka_errors successfully created.
Creating topic karafka_consumers_reports...
Topic karafka_consumers_reports successfully created.
Topic karafka_consumers_metrics already exists.
Creating topic karafka_consumers_states...
Topic karafka_consumers_states successfully created.

Waiting for the topics to synchronize in the cluster.....

Creating consumers state initial record...
Initial consumers state record successfully created.
Initial consumers metrics already exists.

Running data migrations...
bundler: failed to load command: karafka-web (/Users/alex/.rbenv/versions/3.2.3/bin/karafka-web)
Shutting down background worker
Killing session flusher
/Users/alex/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/karafka-web-0.8.1/lib/karafka/web/management/migrations/1704722380_split_listeners_into_active_and_paused_in_metrics.rb:18:in `block (2 levels) in migrate': undefined method `to_i' for {:active=>8, :standby=>0}:Hash (NoMethodError)

                              metric.last[:listeners].to_i
                                                     ^^^^^
Did you mean?  to_s
               to_a
               to_h
```

Running

```bash
$ bundle exec karafka-web install
```

gives no errors.

I tried to manually remove all topics from `kafka` associated with `karafka` (except `consumer_offsets`) but no luck.

Is there anything specific in that topic that I need to find and try to re-run the migrations again?

## Steps to reproduce the problem

Unknown/can not define

## Your setup details

```bash
$ bundle exec karafka info
Karafka version: 2.3.0
Ruby version: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [arm64-darwin23]
Rdkafka version: 0.14.8
Consumer groups count: 8
Subscription groups count: 8
Workers count: 8
Application client id: karafka
Boot file: /Users/alex/projects/optima-api/karafka.rb
Environment: development
License: LGPL-3.0
Shutting down background worker
Killing session flusher
```

**Comment by mensfeld** [comment]
> I tried to manually remove all topics from kafka associated with karafka

not possible. If done well, without running the web UI consumer this would work.

**Comment by mensfeld** [comment]
I think what you ended up looking at the previous issue is some weird state of the web UI topics data that is hard to replicate. I cannot replicate it either at this moment

**Comment by mensfeld** [comment]
Sorry for closing. Misclicked :sweat:

**Comment by juanpedrojose** [comment]
Commenting out `Karafka::Web.enable!` in `karafka.rb`, expectedly, starts the server with no issues.
What I tried:
1. Run the server with `Karafka::Web` disabled
2. Stop the server
4. Enable `Karafka::Web` back
5. Run `bundle exec karafka-web install`
Fails with the same exception as in my first message.

**Comment by mensfeld** [comment]
when your app is installed and you have states you should **not** run install but `karafka-web migrate`

**Comment by mensfeld** [comment]
but this won't change much in your particular state. I first need to understand how you reached a state with separated listeners hash in a place where the expectation is for it to be a number. Can you show me the most recent message content from the metrics topic?

**Comment by mensfeld** [comment]
Cannot reproduce. I will have to get some exact detauks how you were able to reach such state and only then I can help you :(

**Comment by juanpedrojose** [comment]
Oh, such a shame for me, but I found what's causing this issue and probably the issue from my previous topic.

I have this code in my karafka.rb:

```ruby
Karafka::Web.setup do |config|
  config.tracking.interval = 10_000
  config.topics.errors = "#{Karafka::Helper.topic_prefix}karafka_errors"
  config.topics.consumers.reports = "#{Karafka::Helper.topic_prefix}karafka_consumers_reports"
  config.topics.consumers.states = "#{Karafka::Helper.topic_prefix}karafka_consumers_states"
end
```

I need that code to split per-environment based karafka-ui.

One piece that was missing with new `karafka-web`:

```ruby
  config.topics.consumers.metrics = "#{Karafka::Helper.topic_prefix}karafka_consumers_metrics"
```

That resulted in inconsistency between different schemas, or more specifically - where that data is being taken from.

Sorry for false alarm!

**Comment by mensfeld** [comment]
No problem. I was just writing to you asking if you are sure you are not using incorrect topics or not running some consumers with UI computations during reset. Have a nice day and do not hesitate to reach out :) I make a lot of bugs!

P.S. Feel free to join our small slack community: https://slack.karafka.io/ it's much easier to coop there with some debug sessions

**Comment by juanpedrojose** [comment]
@mensfeld 
Just noticed that https://karafka.io/docs/Web-UI-Configuration/#opting-out-of-producers-monitoring also misses that part

```ruby
Karafka::Web.setup do |config|
  env_suffix = Rails.env.to_s

  config.topics.errors = "karafka_errors_#{env_suffix}"
  config.topics.consumers.reports = "karafka_consumers_reports_#{env_suffix}"
  config.topics.consumers.states = "karafka_consumers_states_#{env_suffix}"
end
```

**Comment by mensfeld** [comment]
@juanpedrojose thanks. Not anymore. All references to topics were updated in the docs. I somehow missed that :sweat:
